version: "3.3"
services:
    # front:
    #   build:
    #       dockerfile: Dockerfile
    #       context: ./frontend
    #   environment:
    #       API_URL: http://localhost:5000
    #   depends_on: 
    #       - api
    #   ports:
    #       - "3000:3000"

    api:
        # image: auth
        build:
            dockerfile: Dockerfile
            context: ./backend
        depends_on: 
            - postgres
        environment:
            SECRET_KEY: "randomString"
            DATABASE_URL: postgres://user:password@postgres:5432/db
            NODE_ENV: development
            PORT: 5000
        ports:
            - "5000:5000"

    postgres:
        image: postgres:10.4
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
volumes: 
    pgdata: